### ISSUE TITLE
Hoppers placed at y = -1 don't swallow items.

### ISSUE THREAD

**Issue by mgl512** [tenplus1/hopper#5]
Someone on our server found out that if you walk on hoppers placed at y = -1 and drop items on them, they aren't swallowed. Hoppers placed one block above y = -1 or one block below or at any other height work properly when you do the same thing.

**Comment by tenplus1** [comment]
Very weird, it doesn't take in items immediately but if you leave them a few seconds it seems to work...  Will check up on this.

**Comment by YruamaLairba** [comment]
is it possible to reopen this issue ? i played around with and have more information about it, it's little more complicated than previously explained:

 - First, it happen with all hopper under -1, (a hopper at level -1 will work properly, but hopper at -2, -3 or -4 are affected.
 - Second, the item "spawn" position is important. it can be position of player dropping something, or position of node transformed to a drop by game mechanism (for example, a flower is dropped when you remove the block under it. The problem occur when the drop "spawn" position is above -1.
 - Third, if a drop with a spawn postion below -2 fall near or into a hopper below -2, it suddently activate all hopper around below -2. I mentioned this, because it tend to hide the problem

example to reproduce the problem : 
1 create new world, with hopper mod activated
2 put a hopper at y = -3, 
3 place the player at y=+1 and drop a dirt into the hopper. the dirt will never swallowed.
4 place a new hopper at -3, at some distance of the first hopper.
5 place the player at y = -3 and drop a torch into the hopper. the torch will swallowed, but the dirt will too.

**Comment by tenplus1** [comment]
This seems to be a find object issue near map chunk borders with active_object_count inside abm's, is fixed now.

**Comment by YruamaLairba** [comment]
awesome ! hoppers are working properly now
